export const env = {
  apiKey: '767966187834fddd8ff19b00e6a923f5',
  baseUrl: 'https://api.themoviedb.org/3/movie/now_playing?',
  trendingUrl: 'https://api.themoviedb.org/3/trending/movie/day?',
  latestUrl: 'https://api.themoviedb.org/3/movie/latest?',
  onAirUrl: 'https://api.themoviedb.org/3/tv/on_the_air?',
  headerListUrl: 'https://api.themoviedb.org/3/tv/top_rated?',
  upcomingUrl: 'https://api.themoviedb.org/3/movie/upcoming?',
  // moviesVideos:'https://api.themoviedb.org/3/movie/653346/videos?',
  detailsUrl: 'https://api.themoviedb.org/3/movie/',
  seriesUrl: 'https://api.themoviedb.org/3/tv/popular?',
  seriesGenresUrl: 'https://api.themoviedb.org/3/genre/tv/list',
  moviesVideos: 'https://api.themoviedb.org/3/movie/',
  movieWithGenres: 'https://api.themoviedb.org/3/discover/',
  getGenres: 'https://api.themoviedb.org/3/genre/movie/list',
  getAllMovies: 'https://api.themoviedb.org/3/discover/movie',
  getSeriesUrl: 'https://api.themoviedb.org/3/discover/tv',
  watchlistUrl: 'https://api.themoviedb.org/3/account/null/watchlist?',
  getwatchlist: 'https://api.themoviedb.org/3/account/null/watchlist/movies?',
  searchUrl: 'https://api.themoviedb.org/3/search/movie?',
};
